name: gridbuilding
favicon: null
layout_spectrum: 0.73588
typography_spectrum: 0.18661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7d7c20'
    - '#44474c'
    - '#0f100b'
    - '#a9b17e'
    - '#fff2e4'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
