name: gridbuilding
favicon: null
layout_spectrum: 0.48167
typography_spectrum: 0.83521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbf9'
    - '#d9d0c0'
    - '#b5a79b'
    - '#495445'
    - '#0a0500'
  brandStrength: 0.41602949635125697
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
