name: gridbuilding
favicon: null
layout_spectrum: 0.73588
typography_spectrum: 0.18661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbf9'
    - '#d9d0c0'
    - '#b5a79b'
    - '#495445'
    - '#0a0500'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
