name: gridbuilding
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1b0be'
    - '#f0b66c'
    - '#6a737c'
    - '#020607'
    - '#67481a'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
